apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: myapp
type: Opaque
stringData:
  DB_HOST: taskdb.cvkeqy8c2n2t.ap-south-1.rds.amazonaws.com
  DB_PORT: "3306"
  DB_USER: taskuser
  DB_PASS: password123
  DB_NAME: taskdb
